/* CREATE SEQUENCE */

CREATE SEQUENCE ACCOUNT_SEQ START WITH 2 INCREMENT BY 1 NOORDER;
CREATE SEQUENCE RECIPE_SEQ START WITH 1 INCREMENT BY 1 NOORDER;
CREATE SEQUENCE RECIPE_STEP_SEQ START WITH 1 INCREMENT BY 1 NOORDER;