/* CREATE SEQUENCE */

CREATE SEQUENCE IF NOT EXISTS ACCOUNT_SEQ START WITH 2 INCREMENT BY 1 NOORDER;
CREATE SEQUENCE IF NOT EXISTS RECIPE_SEQ START WITH 1 INCREMENT BY 1 NOORDER;
CREATE SEQUENCE IF NOT EXISTS RECIPE_STEP_SEQ START WITH 1 INCREMENT BY 1 NOORDER;

/* INSERT DATA */

INSERT INTO ACCOUNT(id, username, mail_address, password) VALUES('A0001', 'johndoe', 'johndoe@exmaple.com', 'pwdJohn');