CREATE SEQUENCE IF NOT EXISTS ACCOUNT_SEQ START WITH 2 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS RECIPE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS RECIPE_STEP_SEQ START WITH 1 INCREMENT BY 1;